name: Sample App Configuration Pipeline

trigger: none
pr: none

pool:
   vmImage: 'windows-latest'

jobs:
 - job: Deploy_Config_Dev
   steps:
     - task: JTranTransform@0.1.0
       inputs:
         InputSourcePath:            $(Build.SourcesDirectory)/blanksource.json
         TransformPath:              $(Build.SourcesDirectory)/Config.jtran
         OutputDestinationPath:      $(Build.SourcesDirectory)/Output/output.json
         TransformParameters:        '-environment dev'
