name: Sample App Configuration Pipeline

trigger: none
pr: none

pool:
   name: Default

jobs:
 - job: Deploy_Config_Dev
   steps:
     - task: PowerShell@2
       displayName: 'Display Transform File'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Config.jtran" | Write-Output

     - task: JTranTransform@0.1.1
       inputs:
         InputSourcePath:            $(Build.SourcesDirectory)/blanksource.json
         TransformPath:              $(Build.SourcesDirectory)/Config.jtran
         OutputDestinationPath:      $(Build.SourcesDirectory)/Output/output.json
         TransformParameters:        '-environment dev'

     - task: PowerShell@2
       displayName: 'Display Transform Output'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Output/output.json" | Write-Output
