name: Sample App Configuration Pipeline

trigger: none
pr: none

pool:
   name: Default

jobs:
 - job: Deploy_Config_Dev
   steps:
     - task: PowerShell@2
       displayName: 'Display Source Directory File'
       inputs:
         targetType: 'inline'
         script:     Get-ChildItem -Path "$(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps"

     - task: PowerShell@2
       displayName: 'Display Transform File'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/Config.jtran" | Write-Output

     - task: JTranTransform@0.1.5
       inputs:
         InputSourcePath:            $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/blanksource.json
         TransformPath:              $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/Config.jtran
         OutputDestinationPath:      $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/output.json
         TransformParameters:        '-environment dev -Phrase hello'

     - task: PowerShell@2
       displayName: 'Display Transform Output'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/output.json" | Write-Output
