name: Sample App Configuration Pipeline

trigger: none
pr: none

pool:
   name: Default

jobs:
 - job: Deploy_Config_Dev
   steps:
     - task: JTranTransform@1.0.2
       displayName: 'Transform Configuration File'
       inputs:
         InputSourcePath:            $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/blanksource.json
         TransformPath:              $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/config.jtran
         OutputDestinationPath:      $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps
         MultipleOutput:             true
         TransformParameters:        '-environment dev -Phrase hello'

     - task: PowerShell@2
       displayName: 'Display Transform Output'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/nonkeyvault.json" | Write-Output

     - task: PowerShell@2
       displayName: 'Display Transform Output'
       inputs:
         targetType: 'inline'
         script:     Get-Content "$(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/keyvault.json" | Write-Output

     ################################################################################################
     ### Deploy the non-keyvault entries (this will delete all current entries)
     ################################################################################################
     
     - task: AzureAppConfigurationPush@3
       displayName: 'Push non-keyvault configuration entries to Azure App Configuration'
       inputs:
         azureSubscription:          'spn-jtran-cicd-dev'
         AppConfigurationEndpoint:   'https://appcs-jtran-cicd-dev.azconfig.io'
         ConfigurationFile:          $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/nonkeyvault.json
         Separator:                  ','
         Strict:                     true
     
     ################################################################################################
     ### Deploy the keyvault references
     ################################################################################################
     
     - task: AzureAppConfigurationPush@3
       displayName: 'Push Keyvault References to Azure App Configuration'
       inputs:
         azureSubscription:          'spn-jtran-cicd-dev'
         AppConfigurationEndpoint:   'https://appcs-jtran-cicd-dev.azconfig.io'
         ConfigurationFile:          $(Build.SourcesDirectory)/Samples/Deployment/AzureDevOps/keyvault.json
         Separator:                  ','
         ContentType:                'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
         Strict:                     false
